import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const source = await readFile(join(dir, "../prisma/schema.prisma"), "utf8");
const { prismaMajor } = JSON.parse(
  await readFile(join(dir, "schema-options.json"), "utf8"),
);
const enums = new Set(
  [...source.matchAll(/enum\s+(\w+)\s*\{/g)].map((m) => m[1]),
);
const models = new Set(
  [...source.matchAll(/model\s+(\w+)\s*\{/g)].map((m) => m[1]),
);
const numericScales = [];
let model;
let schema = source
  .replace(/generator\s+\w+\s*\{[^}]*\}\s*/g, "")
  .replace(/datasource\s+\w+\s*\{[^}]*\}\s*/g, "");
schema = schema
  .split(/\r?\n/)
  .map((line) => {
    const start = line.match(/^model\s+(\w+)/);
    if (start) model = start[1];
    const decimal = line.match(/^(\s*)(\w+)(\s+)Decimal(\??)(.*)$/);
    if (decimal) {
      const scale = Number(
        decimal[5].match(/@db\.Decimal\(\d+,\s*(\d+)\)/)?.[1],
      );
      if (!Number.isInteger(scale))
        throw new Error(`Decimal scale is missing: ${model}.${decimal[2]}`);
      numericScales.push({ model, field: decimal[2], scale });
      line = `${decimal[1]}${decimal[2]}${decimal[3]}BigInt${decimal[4]}${decimal[5]}`;
      line = line.replace(/@default\((-?\d+(?:\.\d+)?)\)/, (_match, value) => {
        const [whole, fraction = ""] = value.split(".");
        if (fraction.length > scale)
          throw new Error("Default would lose decimal precision");
        return `@default(${BigInt(whole + fraction.padEnd(scale, "0"))})`;
      });
    }
    const array = line.match(/^(\s*)(\w+)(\s+)(\w+)\[\](.*)$/);
    if (array && (array[4] === "String" || enums.has(array[4]))) {
      let tail = array[5].replace(
        /@default\(\[([^\]]*)\]\)/,
        (_match, content) => {
          const values = content.trim()
            ? content.split(",").map((v) => v.trim().replace(/^"|"$/g, ""))
            : [];
          return `@default(${JSON.stringify(JSON.stringify(values))})`;
        },
      );
      line = `${array[1]}${array[2]}${array[3]}Json${tail}`;
    }
    return line.replace(/\s+@db\.\w+(?:\([^)]*\))?/g, "").trimEnd();
  })
  .join("\n");
const generator =
  prismaMajor >= 7
    ? 'generator client {\n  provider = "prisma-client"\n  output = "../.generated/d1"\n  runtime = "cloudflare"\n}\n'
    : 'generator client {\n  provider = "prisma-client-js"\n  output = "../.generated/d1"\n  engineType = "client"\n}\n';
const datasource = `datasource db {\n  provider = "sqlite"\n${prismaMajor < 7 ? '  url = "file:./development.sqlite"\n' : ""}}\n`;
schema =
  "// Generated by npm run db:d1:sync-schema; do not edit manually.\n" +
  generator +
  "\n" +
  datasource +
  "\n" +
  schema;
await writeFile(join(dir, "schema.prisma"), schema);
const tables = [...schema.matchAll(/model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)].map(
  (m) => ({
    name: m[2].match(/@@map\("([^"]+)"\)/)?.[1] ?? m[1],
    columns: [...m[2].matchAll(/^\s*(\w+)\s+(\w+)(\[\]|\?)?([^\n]*)/gm)]
      .filter((f) => !models.has(f[2]))
      .map((f) => ({
        name: f[4].match(/@map\("([^"]+)"\)/)?.[1] ?? f[1],
        type: f[2],
      })),
  }),
);
await writeFile(
  join(dir, "contract.json"),
  JSON.stringify({ tables, numericScales }, null, 2) + "\n",
);
console.log(
  `Generated D1 schema: ${tables.length} models, ${numericScales.length} scaled numeric fields`,
);
